# Generated by Django 4.1.2 on 2022-11-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(max_length=255, upload_to='pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('original_price', models.FloatField(blank=True, default=0)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_rate', models.FloatField(blank=True, default=0)),
                ('rating_average', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0)),
                ('review_count', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tech_ecommerce.categories')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authenticate.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Speficication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('cpu_speed', models.CharField(blank=True, max_length=100, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('rom', models.CharField(blank=True, max_length=100, null=True)),
                ('screen_size', models.CharField(blank=True, max_length=100, null=True)),
                ('battery_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('chip_set', models.CharField(blank=True, max_length=100, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tech_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Màu', 'Màu'), ('Dung lượng', 'Dung lượng')], default='Màu', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='tech_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChilds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(blank=True, default=0)),
                ('inventory_status', models.BooleanField(blank=True, default=True)),
                ('selected', models.BooleanField(blank=True, default=False)),
                ('thumbnail_url', models.URLField(blank=True, max_length=100, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_childs', to='tech_ecommerce.products')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_childs', to='authenticate.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('product_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tech_ecommerce.productchilds')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tech_ecommerce.productvariants')),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(blank=True, default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('time_interactive', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive', to='tech_ecommerce.products')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive', to='authenticate.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ImgProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_products', to='tech_ecommerce.products')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('total_price', models.FloatField(blank=True, default=0)),
                ('product_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='tech_ecommerce.productchilds')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='authenticate.userprofile')),
            ],
        ),
    ]
