# Generated by Django 4.1.3 on 2022-12-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='icon',
        ),
    ]
