# Generated by Django 4.1.1 on 2022-11-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('order_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay_int',
            new_name='pay_in',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='order_payment.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='authenticate.seller'),
        ),
        migrations.AlterField(
            model_name='payin',
            name='received_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
